"""create analysis tables

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_sessions_id"), "analysis_sessions", ["id"], unique=False
    )
    op.create_table(
        "text_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("pred_label", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("true_label", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["analysis_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_text_analyses_id"), "text_analyses", ["id"], unique=False)
    op.create_index(
        op.f("ix_text_analyses_session_id"),
        "text_analyses",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_text_analyses_session_id"), table_name="text_analyses")
    op.drop_index(op.f("ix_text_analyses_id"), table_name="text_analyses")
    op.drop_table("text_analyses")
    op.drop_index(op.f("ix_analysis_sessions_id"), table_name="analysis_sessions")
    op.drop_table("analysis_sessions")
    # ### end Alembic commands ###
